TOTAL_SPACES = 6
PAYMENT_VALID_MINUTES = 2
TICKET_EXPIRATION_HOURS = 48

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 700

SPACE_WIDTH = 110
SPACE_HEIGHT = 180

ENTRY_SERVO_COMMAND = "OPEN_ENTRY"
EXIT_SERVO_COMMAND = "OPEN_EXIT"
LCD_PREFIX = "LCD:"
PARKING_FULL_COMMAND = "PARKING_FULL"

TARIFA_MINIMA = 0.50
TARIFA_POR_HORA= 0.508
