TOTAL_SPACES = 6
PAYMENT_VALID_MINUTES = 2
TICKET_EXPIRATION_HOURS = 48

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 700

SPACE_WIDTH = 110
SPACE_HEIGHT = 180

ENTRY_SERVO_COMMAND = "OPEN_ENTRY"
EXIT_SERVO_COMMAND = "OPEN_EXIT"
LCD_PREFIX = "LCD:"
PARKING_FULL_COMMAND = "PARKING_FULL"

TARIFA_MINIMA = 0.50
TARIFA_POR_HORA= 0.508

# CONTROL DE BARRERA POR SENSOR DE PASO
ENTRY_SENSOR_ENABLED = True
ENTRY_SENSOR_KEYWORDS = ["ENTRY_PASS", "PASO_ENTRADA", "CAR_PASSED", "SENSOR_ENTRADA"]
ENTRY_SENSOR_MAX_WAIT_SECONDS = 0
ENTRY_BARRIER_MIN_OPEN_SECONDS = 0
ENTRY_BARRIER_CLOSE_DELAY_SECONDS = 3

# CONFIGURACIÓN IMPRESORA BLUETOOTH
BLUETOOTH_PRINTER_ENABLED = True
BLUETOOTH_PRINTER_MAC = "86:67:7a:e8:30:09"
BLUETOOTH_PRINTER_WINDOWS_PORT = "/dev/cu.MPT-II_3009"
BLUETOOTH_PRINTER_BAUDRATE = 9600
